---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-admin
  labels:
    app: mysql-admin
    version: 4.7.7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-admin
      version: 4.7.7
  template:
    metadata:
      labels:
        app: mysql-admin
        version: 4.7.7
    spec:
      containers:
      - name: mysql-admin
        image: adminer
        ports:
        - containerPort: 8080
        env:  
        - name: MYSQL_ROOT_PASSWORD
          value: '123456'
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-admin
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: mysql-admin
    version: 4.7.7
---