---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
    version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      version: latest
  template:
    metadata:
      labels:
        app: wordpress
        version: latest
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80
        env:  
        - name: WORDPRESS_DB_HOST
          value: 'mysql-server:3306'
        - name: WORDPRESS_DB_USER
          value: 'root'
        - name: WORDPRESS_DB_PASSWORD
          value: '123456'
        - name: WORDPRESS_DB_NAME
          value: 'wordpress'
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: wordpress
    version: latest
---